### ISSUE TITLE
Refactor HTTP requests that are based on curl

### ISSUE THREAD

**Issue by illya-havsiyevych** [epam/quanthub-portal#28]
- [x] https://github.com/epam/quanthub-portal/blob/c62632dc915aecab7f1c2794f4af92bb8059681d/modules/quanthub_core/src/PowerBIEmbedConfigs.php#L119
- [x] https://github.com/epam/quanthub-portal/blob/c62632dc915aecab7f1c2794f4af92bb8059681d/modules/quanthub_core/src/PowerBIEmbedConfigs.php#L167

**Comment by artemboyko43** [comment]
https://github.com/epam/quanthub-portal/pull/62 fixed here
